name: 'Build 3DS-RPC'
on: [push, pull_request, release]

jobs:
  build:
    name: 'Build 3DS-RPC'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'macos-latest']
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # Windows Build
    - name: "Build"
      if: matrix.os == 'windows-latest'
      run: cd scripts && ./build.bat

    # macOS Build
    - name: "Build"
      if: matrix.os == 'macos-latest'
      run: |
        ./scripts/build.sh &&
        cd ./dist &&
        zip -yr "3DS-RPC Mac.zip" 3DS-RPC.app/

    # For normal commits, upload the created artifact.
    - uses: actions/upload-artifact@v4
      with:
        path: dist/3DS-RPC*

    # If this is a release, additionally attach
    # the created applications to the release.
    - name: "Upload Build"
      if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v2
      with:
        files: dist/3DS-RPC*
